version: '2'

services:
  node:
    container_name: node
    build: 
      context: .
      dockerfile: nodeDockerfile
    ports:
     - "3000:3000"
    volumes:
     - ./:/var/www
    working_dir: /var/www
    networks:
     - nodeapp-network
  
  ngnix:
    container_name: ngnix
    build: 
      context: .
      dockerfile: ngnixDockerfile
    ports:
     - "80:80"
    networks:
     - nodeapp-network
  
  redis:
    container_name: redis
    build: 
      context: .
      dockerfile: redisDockerfile
    ports:
     - "6379:6379"
    networks:
     - nodeapp-network
  
  mysql:
    container_name: mysql
    build: 
      context: .
      dockerfile: mysqlDockerfile
    ports:
     - "3306:3306"
    networks:
     - nodeapp-network
      
networks:
  nodeapp-network:
    driver: bridge